/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BaristaRouteImport } from './routes/barista'
import { Route as IndexRouteImport } from './routes/index'

const BaristaRoute = BaristaRouteImport.update({
  id: '/barista',
  path: '/barista',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/barista': typeof BaristaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/barista': typeof BaristaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/barista': typeof BaristaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/barista'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/barista'
  id: '__root__' | '/' | '/barista'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BaristaRoute: typeof BaristaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/barista': {
      id: '/barista'
      path: '/barista'
      fullPath: '/barista'
      preLoaderRoute: typeof BaristaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BaristaRoute: BaristaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
